project: image_regression_final
WANDB_DIR: out
program: src/reg_grownet.py

method: random
metric:
  goal: maximize
  name: Ensemble/psnr
name: grownet_weakPlateauF0.1P2_ensembleDecay0.95AndPlateauF0.5P2_ResetWeak
parameters:
  scale:
    value: 0.1
  num_nets:
    value: 200
  shuffle_batches:
    value: True
  epochs_per_stage:
    values: [ 1, 5, 10, 20, 50, 100 ]
  epochs_per_correction:
    values: [ 0, 1, 5, 10, 20, 50, 100 ]
  optimizer:
    values: [ adam, adamW, sgd ]
  hidden_size:
    values: [ 4, 8, 16, 32, 64, 128, 256 ]
  hidden_layers:
    values: [ 1, 2, 3, 4 ]
  acc_gradients:
    values: [ True, False ] # FIXME: check this
  model:
    values: [ siren ] # nn
  B_scale:
    values: [ 2, 5, 10, 20, 40 ]
  batch_size:
    values: [ 2000, 5000, 10000, 20000 ]
  lr_model:
    distribution: log_uniform
    min: -9.21034037 # 0.001
    max: -4.60517019 # 0.01
  lr_ensemble:
    distribution: log_uniform
    min: -9.21034037 # 0.001
    max: -4.60517019 # 0.01
#early_terminate:
#  type: hyperband
#  max_iter: 30
#  s:2